version: 2

models:
  - name: int_transactions
    description: "Cleaned and filtered bank transactions derived from raw VARIANT data."

    columns:

      - name: transactionid
        description: "Unique identifier for the transaction."
        tests:
          - not_null

      - name: accountid
        description: "Unique identifier for the bank account associated with the transaction."
        tests:
          - not_null

      - name: transactionamount
        description: "Amount of the transaction."
        tests:
          - not_null

      - name: transactiondate
        description: "Date and time of the transaction."

      - name: transactiontype
        description: "Type of transaction (Debit/Credit)."

      - name: location
        description: "City where the transaction happened."

      - name: deviceid
        description: "Identifier of the device used for the transaction."

      - name: ipaddress
        description: "IP address of the transaction."

      - name: merchantid
        description: "Merchant identifier for the transaction."

      - name: channel
        description: "Transaction channel (ATM / Online)."
        tests:
          - accepted_values:
              values: ['ATM', 'Online']

      - name: customerage
        description: "Age of the customer at the time of the transaction."

      - name: customeroccupation
        description: "Occupation of the customer."

      - name: transactionduration
        description: "Duration of the transaction in seconds."

      - name: loginattempts
        description: "Number of login attempts made by the customer."

      - name: accountbalance
        description: "Balance of the bank account."

      - name: filename
        description: "Source file name from S3 ingestion."

      - name: created_at
        description: "Timestamp when the record was ingested."
        tests:
          - not_null