-- LIST RAW_DATA 
list @BANK_TRANSACTIONS;

-- CREATE FILE FORMAT
CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT
TYPE = PARQUET
COMPRESSION = AUTO;

-- BRONZE LAYER
INSERT INTO BANK_TRANSACTIONS_BRONZE
SELECT DISTINCT 
CAST($1 AS VARIANT) raw_data,
metadata$filename, 
current_timestamp created_at
FROM @BANK_TRANSACTIONS 
(FILE_FORMAT => 'PARQUET_FORMAT');