CREATE OR REPLACE PROCEDURE load_bronze_transactions()
RETURNS STRING
LANGUAGE SQL
AS
$$

TRUNCATE TABLE BANK_TRANSACTIONS_BRONZE;

INSERT INTO BANK_TRANSACTIONS_BRONZE
SELECT DISTINCT 
    CAST($1 AS VARIANT) AS raw_data,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP AS created_at
FROM @BANK_TRANSACTIONS
(FILE_FORMAT => 'PARQUET_FORMAT');

SELECT 'BRONZE DATA LOADED';

$$;